# Generated by Django 5.1.1 on 2024-10-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horariosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('diurno', 'Diurno'), ('vespertino', 'Vespertino')], max_length=10)),
            ],
        ),
    ]
