# Generated by Django 5.1.1 on 2024-10-11 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horariosApp', '0002_bloque'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horariosApp.bloque')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horariosApp.sala')),
            ],
            options={
                'unique_together': {('sala', 'bloque')},
            },
        ),
    ]
