# Generated by Django 5.1.1 on 2024-11-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horariosApp', '0003_disponibilidadsala'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='cant_bloques',
            field=models.IntegerField(default=0),
        ),
    ]
