# Generated by Django 5.1.1 on 2024-11-25 00:32

from django.db import migrations


def create_vista_horarios(apps, schema_editor):
    # SQL para crear la vista optimizada
    sql = """
    CREATE VIEW vista_horarios AS
    SELECT 
        h.id AS horario_id,
        s.id AS seccion_id,
        s.programa_estudio AS seccion_programa_estudio,
        s.asignatura AS seccion_asignatura,
        s.cant_alumnos AS seccion_cant_alumnos,
        s.subseccion AS seccion_subseccion,
        s.hrs_asignatura AS seccion_hrs_asignatura,
        s.jornada AS seccion_jornada,
        s.cant_bloques AS seccion_cant_bloques,
        sala.codigo_iso AS sala_codigo_iso,
        sala.descripcion AS sala_descripcion,
        sala.cupo_estandar AS sala_cupo,
        b.dia AS bloque_dia,
        b.hora_inicio AS bloque_hora_inicio,
        b.hora_fin AS bloque_hora_fin
    FROM horariosapp_horario h
    JOIN horariosapp_seccion s ON h.seccion_id = s.id
    JOIN horariosapp_disponibilidadsala ds ON h.disponibilidad_sala_id = ds.id
    JOIN horariosapp_sala sala ON ds.sala_id = sala.id
    JOIN horariosapp_bloque b ON ds.bloque_id = b.id;
    """
    # Ejecuta el SQL para crear la vista
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(sql)


def drop_vista_horarios(apps, schema_editor):
    # SQL para eliminar la vista
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP VIEW IF EXISTS vista_horarios;")


class Migration(migrations.Migration):

    dependencies = [
        ('horariosApp', '0005_horario'),  # Ajusta según el número de tu última migración
    ]

    operations = [
        migrations.RunPython(create_vista_horarios, reverse_code=drop_vista_horarios),
    ]