# Generated by Django 5.1.1 on 2024-11-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horariosApp', '0006_create_vista_horarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_id', models.IntegerField()),
                ('cod_asignatura', models.CharField(max_length=10)),
                ('asignatura', models.CharField(max_length=100)),
                ('hrs_asignatura', models.IntegerField()),
                ('seccion', models.CharField(max_length=10)),
                ('cant_bloques', models.IntegerField()),
                ('sala_codigo_iso', models.CharField(max_length=10)),
                ('tipo_sala', models.CharField(max_length=100)),
                ('sala_disponible', models.BooleanField()),
                ('bloque_dia', models.CharField(max_length=10)),
                ('bloque_hora_inicio', models.TimeField()),
                ('bloque_hora_fin', models.TimeField()),
                ('bloque_tipo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vista_horarios',
                'managed': False,
            },
        ),
    ]
